// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcvcSJQ-3v4glh2Ho89QOB6v8h-dQl_FQ',
    appId: '1:89975692509:android:895c284f1757ea498e8f34',
    messagingSenderId: '89975692509',
    projectId: 'test-79b46',
    databaseURL: 'https://test-79b46-default-rtdb.firebaseio.com',
    storageBucket: 'test-79b46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjFR3Oj9GG8RO7rQg2oj5LXD0DKPOWIgg',
    appId: '1:89975692509:ios:af741b4a06e4f90a8e8f34',
    messagingSenderId: '89975692509',
    projectId: 'test-79b46',
    databaseURL: 'https://test-79b46-default-rtdb.firebaseio.com',
    storageBucket: 'test-79b46.appspot.com',
    iosClientId: '89975692509-bevt577fg2m2tftkknlmmqbk43k5tuhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryStore',
  );
}
